id: hl7.fhir.us.core
canonical: http://hl7.org/fhir/us/core
name: USCore
status: active
version: 3.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: Build CI
publisher:
  name: HL7 US Realm Steering Committee
  url: http://www.healthit.gov
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
template: fhir.base.template#0.1.0

menu:
  Home: index.html
  Artifacts: artifacts.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true